# 配置端口信息
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: song-service-route
          uri: lb://song-module
          predicates:
            - Path=/song/**
          filters:
            - StripPrefix=1
        - id: activity-service-route
          uri: lb://activity-module
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1
        - id: user-service-route
          uri: lb://user-module
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka.com/eureka
  instance:
    prefer-ip-address: true


