apiVersion: v1
kind: Service
metadata:
  labels:
    cloud.netease.com/name: eureka
  name: service-eureka
  namespace: song
spec:
  ports:
    - name: api-port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    cloud.netease.com/name: eureka
  type: ClusterIP